version: '3.1'

services:

  postgresDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: adminPassword123
      POSTGRES_USER: admin
      POSTGRES_DB: users
    ports:
      - 5432:5432